from django.urls import path, re_path, include
from . import views
from .views import DashDataView, LoginView, DashDataInsert, DashDataDelete, DashDataManualInsert, DashDataSearch

urlpatterns = [
    path('', views.home, name='home'),
    path('pesquisadores/', views.pesq_list, name='pesq_list'),
    path('pesquisador/<int:pk>/', views.pesq_detail, name='pesq_detail'),
    path('linha/<int:pk>/', views.linha_detail, name='linha_detail'),
    path('cadastrar-usuario/', views.usuario_cadastrar, name='usuario_cadastrar'),
    path('atualizar-usuario/', views.update_profile, name='update_profile'),
    path('paper-add/', views.insert_paper, name='insert_paper'),
    re_path(r'^paper-delete/(?P<pk>\b\d{1,4}\b)/$', views.delete_paper, name='delete_paper'),
    re_path(r'^curriculum-add/(?P<campo>\w)/$', views.insert_achievement, name='insert_achievement'),
    re_path(r'^curriculum-delete/(?P<pk>\b\d{1,4}\b)/$', views.delete_achievement, name='delete_achievement'),
    path('dashdata-view/',DashDataView.as_view(), name='dashdata-all'),
    path('dashdata-insert/',DashDataInsert.as_view(), name='dashdata-insert'),
    path('dashdata-delete/',DashDataDelete.as_view(), name='dashdata-delete'),
    path('sensor_delete/', views.sensor_delete, name='sensor_delete'),
    path('sensor_update/', views.sensor_update, name='sensor_update'),
    path('dashdata-manual-insert/',DashDataManualInsert.as_view(), name='dashdata-manual-insert'),
    path('dashdata-search/',DashDataSearch.as_view(), name='dashdata-search'),
    path('dashdata-download/',views.dashdata_download, name='dashdata-download'),
    path('auth/login', LoginView.as_view(), name='auth-login'),
    path('curriculum/', views.pesq_detail_add, name='pesq_detail_add'),
    path('cadastrar/linha/', views.linha_cadastrar, name='linha_cadastrar'),
    path('linhas-de-pesquisa/', views.linhas, name='linhas'),
    path('dashboard_chart/', views.dashboard_chart, name='dashboard_chart'),
    path('dashboard_insert_data/', views.dashboard_insert_data, name='dashboard_insert_data'),
    path('dashboard/insert-sensor/', views.insert_sensor, name='insert_sensor'),
    path('dashboard/chart_detail/', views.dashboard_chart_detail, name='dashboard_chart_detail'),
    path('dashboard/chart_data/', views.dashboard_chart_data, name='dashboard_chart_data'),
    path('dashboard_data_amount/', views.dashboard_data_amount, name='dashboard_data_amount'),
    path('dashboard_all_data/', views.dashboard_all_data, name='dashboard_all_data'),
    path('dashboard/chart_real_time/', views.dashboard_real_time, name='dashboard_real_time'),
    path('dashboard_chart_plot/', views.chart_data, name='chart_data'),
    path('dashboard/inserir-dados/', views.dashboard_insert_data_page, name='dashboard_insert_data_page'),
    path('dashboard_stats/', views.dashboard_stats, name='dashboard_stats'),
    path('dashboard_update_data/', views.dashboard_update_data, name='dashboard_update_data'),
]
