# Generated by Django 2.0.9 on 2018-10-25 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisador',
            name='pesquisador',
        ),
        migrations.RemoveField(
            model_name='pesquisador',
            name='pesquisas',
        ),
        migrations.AddField(
            model_name='customuser',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='graduacao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pesquisas',
            field=models.ManyToManyField(to='pesq.Linhas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='titulo',
            field=models.CharField(choices=[('B', 'Bacharel'), ('M', 'Mestre'), ('D', 'Doutor(a)')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='Pesquisador',
        ),
    ]
