# Generated by Django 2.0.9 on 2018-10-25 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0003_remove_customuser_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('graduacao', models.CharField(max_length=200)),
                ('titulo', models.CharField(choices=[('B', 'Bacharel'), ('M', 'Mestre'), ('D', 'Doutor(a)')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, upload_to='media')),
                ('pesquisas', models.ManyToManyField(to='pesq.Linhas')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='graduacao',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pesquisas',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='pesquisador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
