# Generated by Django 2.0.9 on 2018-10-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0005_auto_20181025_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('graduacao', models.CharField(blank=True, max_length=200)),
                ('titulo', models.CharField(blank=True, choices=[('B', 'Bacharel'), ('M', 'Mestre'), ('D', 'Doutor(a)')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, upload_to='media')),
                ('pesquisas', models.ManyToManyField(to='pesq.Linhas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pesquisador',
            name='pesquisas',
        ),
        migrations.RemoveField(
            model_name='pesquisador',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Pesquisador',
        ),
    ]
