# Generated by Django 2.0.9 on 2018-10-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0006_auto_20181026_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('A', 'Formação Acadêmica'), ('B', 'Formação Complementar'), ('C', 'Publicação'), ('D', 'Produtos, Inovações e Aplicações')], max_length=1)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('texto', models.TextField()),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
