# Generated by Django 2.0.9 on 2018-10-29 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0007_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
