# Generated by Django 2.0.9 on 2018-10-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0008_achievement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
