# Generated by Django 2.0.9 on 2018-10-30 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0010_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('experimento', models.CharField(blank=True, max_length=200)),
                ('dado', models.FloatField()),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
