# Generated by Django 2.0.9 on 2018-10-31 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0013_auto_20181031_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashdata',
            name='pesquisador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisador', to=settings.AUTH_USER_MODEL),
        ),
    ]
