# Generated by Django 2.0.9 on 2018-12-04 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0014_auto_20181031_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField()),
                ('description', models.TextField()),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dashdata',
            name='pesquisador',
        ),
        migrations.AlterField(
            model_name='dashdata',
            name='experimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimento', to='pesq.Experimento'),
        ),
    ]
