# Generated by Django 2.0.9 on 2018-12-04 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0015_auto_20181204_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
