# Generated by Django 2.0.9 on 2018-12-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0016_experimento_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
