# Generated by Django 2.0.9 on 2018-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0017_auto_20181204_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='last_data',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=12),
        ),
    ]
