# Generated by Django 2.0.9 on 2018-12-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0018_experimento_last_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='last_data',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
