# Generated by Django 2.0.9 on 2018-12-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0020_auto_20181210_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='last_data',
            field=models.FloatField(default=0),
        ),
    ]
