# Generated by Django 2.1.7 on 2019-02-13 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0021_auto_20181211_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
