# Generated by Django 2.1.7 on 2019-02-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesq', '0022_auto_20190213_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='/media/avatar.png', upload_to='media'),
        ),
    ]
